# Generated by Django 2.1.4 on 2019-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_content',
            field=models.BooleanField(default=False),
        ),
    ]
