# Generated by Django 2.1.4 on 2019-01-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_approved_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_content',
            new_name='approved_comment',
        ),
    ]
